<a href="https://colab.research.google.com/github/RishavRajSharma/AI_LAB/blob/main/Exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array = np.array([12, 5, 7, 3, 19, 1, 8])

print("Original array:")
print(array)

sorted_array = np.sort(array)

print("\nSorted array (ascending):")
print(sorted_array)

sorted_desc = np.sort(array)[::-1]

print("\nSorted array (descending):")
print(sorted_desc)


Original array:
[12  5  7  3 19  1  8]

Sorted array (ascending):
[ 1  3  5  7  8 12 19]

Sorted array (descending):
[19 12  8  7  5  3  1]
